name: Code Analysis

on:
  pull_request:
  push:

jobs:
  code_analysis:
    strategy:
      fail-fast: false
      matrix:
        php:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

        actions:
          - name: PHPStan
            run: composer run phpstan

          - name: Unit tests
            run: composer run test

        versions:
          - name: highest
            experimental: false

          - name: lowest
            experimental: true

    name: ${{ matrix.actions.name }} at PHP ${{ matrix.php }} (${{ matrix.versions.name }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # see https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: none

      - name: Install Composer deps
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: "${{ matrix.versions.name }}"

      - name: Run ${{ matrix.actions.name }}
        run: ${{ matrix.actions.run }}
        continue-on-error: ${{ matrix.versions.experimental }}
