name: Code Analysis

on:
  pull_request:
  push:

jobs:
  code_analysis:
    strategy:
      fail-fast: false
      matrix:
        php:
        #  - '7.1' # incompatible tester
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
        #  - '8.1' # not yet compatible (PHP 8.1 RC2)
        actions:
          - name: PHPStan
            run: composer phpstan

          - name: Unit tests
            run: vendor/bin/tester tests -s -C

    name: ${{ matrix.actions.name }} at PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      # see https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: none


      # see https://github.com/actions/cache/blob/main/examples.md#php---composer
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            **/composer.lock
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}


      - name: Install Composer
        run: composer install --no-progress

      - run: ${{ matrix.actions.run }}
